# Generated by Django 4.1.3 on 2022-11-20 20:27

import anime.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=anime.models.user_directory_path)),
                ('slug', models.SlugField(max_length=250, unique=True, unique_for_date='concluido')),
                ('concluido', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('emision', 'En emision'), ('concluido', 'Concluido')], default='emision', max_length=10)),
            ],
            options={
                'ordering': ('-concluido',),
            },
        ),
    ]
